coverage:
  precision: 2
  round: down
  range: "70...100"

  status:
    project: yes
    patch: 
      default:
        target: 100%
    changes: yes

parsers:
  gcov:
    branch_detection:
      conditional: yes
      loop: yes
      method: no
      macro: no

comment:
  layout: "header, diff"
  behavior: default
  require_changes: no
