version: 2.1

orbs:
  codecov: codecov/codecov@1.0.2

executors:
  node8:
    docker:
      - image: circleci/node:8.16.1

commands:
  checkout_and_install:
    steps:
      - checkout
      - run:
          name: Install Dependencies
          command: npm i

jobs:
  lint:
    executor: node8
    steps:
      - checkout_and_install
      - run:
          name: Lint
          command: npm run lint 

  test:
    executor: node8
    steps:
      - checkout_and_install
      - run:
          name: Test
          command: npm test
      - codecov/upload:
          file: /test-results/jest/lcov.info

  build:
    executor: node8
    steps:
      - checkout_and_install
      - run: 
          name: Build
          command: npm run build

workflows:
  version: 2
  default:
    jobs:
      - lint
      - test
      - build
